import { Feather, MaterialCommunityIcons } from "@expo/vector-icons";
import React, { useEffect, useState } from "react";
import {
  ActionSheetIOS,
  Alert,
  Platform,
  Pressable,
  ScrollView,
  Share,
  StyleSheet,
  Text,
  View,
} from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import * as Haptics from "expo-haptics";
import AsyncStorage from "@react-native-async-storage/async-storage";
import * as FileSystem from "expo-file-system";
import * as Sharing from "expo-sharing";
import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } from "docx";
import { AlertBanner } from "@/components/AlertBanner";
import { Colors } from "@/constants/colors";
import { useDashboard } from "@/context/DashboardContext";
import { ENV } from "@/config/env";

type Filter = "all" | "active" | "critical" | "high" | "medium";

const LANGUAGE_FLAGS = [
  { code: "en", flag: "🇬🇧", label: "EN", name: "English" },
  { code: "hi", flag: "🇮🇳", label: "HI", name: "Hindi" },
  { code: "ur", flag: "🇵🇰", label: "UR", name: "Urdu" },
  { code: "ar", flag: "🇸🇦", label: "AR", name: "Arabic" },
  { code: "fr", flag: "🇫🇷", label: "FR", name: "French" },
];

export default function AlertsScreen() {
  const insets = useSafeAreaInsets();
  const { alerts, dismissAlert, deviceName, deviceLocation } = useDashboard();
  const [filter, setFilter] = useState<Filter>("active");
  const [selectedLanguage, setSelectedLanguage] = useState("en");
  const [generatingReport, setGeneratingReport] = useState(false);

  const topPad = Platform.OS === "web" ? 67 : insets.top;
  const bottomPad = Platform.OS === "web" ? 34 : insets.bottom;

  useEffect(() => {
    AsyncStorage.getItem("unifyos_language").then(lang => {
      if (lang) setSelectedLanguage(lang);
    });
  }, []);

  const filteredAlerts = alerts.filter(a => {
    if (filter === "active") return !a.dismissed && a.severity !== "NORMAL";
    if (filter === "critical") return a.severity === "CRITICAL";
    if (filter === "high") return a.severity === "HIGH";
    if (filter === "medium") return a.severity === "MEDIUM";
    return true;
  });

  const activeCount = alerts.filter(a => !a.dismissed && a.severity !== "NORMAL").length;
  const criticalCount = alerts.filter(a => a.severity === "CRITICAL").length;

  const topCritical = filteredAlerts.find(a => a.severity === "CRITICAL" && !a.dismissed);

  const dismissAll = () => {
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium);
    filteredAlerts.forEach(a => dismissAlert(a.id));
  };

  function handleLanguageSelect(code: string) {
    setSelectedLanguage(code);
    AsyncStorage.setItem("unifyos_language", code);
    Haptics.selectionAsync();
  }

  function buildExportText() {
    const header = [
      "═══════════════════════════════════",
      " UnifyOS — Alert Export Log",
      ` Generated: ${new Date().toLocaleString()}`,
      ` Device: ${deviceName}`,
      ` Location: ${deviceLocation}`,
      "═══════════════════════════════════",
      "",
    ].join("\n");

    const body = alerts.slice(0, 100).map(a => [
      `[${a.severity}] — ${new Date(a.createdAt).toLocaleString()}`,
      ` Location: ${a.deviceLocation}`,
      ` Confidence: ${a.confidence}%`,
      a.triggeredSensors?.length ? ` Triggered: ${a.triggeredSensors.join(", ")}` : "",
      ` Message: ${a.message}`,
      a.aiAction ? ` Action: ${a.aiAction}` : "",
      " ─────────────────────────────────",
    ].filter(Boolean).join("\n")).join("\n");

    const footer = [
      "",
      `Total alerts: ${alerts.length}`,
      `Critical: ${alerts.filter(a => a.severity === "CRITICAL").length} | High: ${alerts.filter(a => a.severity === "HIGH").length} | Medium: ${alerts.filter(a => a.severity === "MEDIUM").length}`,
      "Generated by UnifyOS — Team BlackBit",
      "Google Solution Challenge 2026",
    ].join("\n");

    return header + body + footer;
  }

  async function handleGenerateReport() {
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium);
    setGeneratingReport(true);
    try {
      console.log("📄 Requesting incident report generation from backend...");
      const res = await fetch(`${ENV.BACKEND_URL}/generate-incident-report`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ venue: deviceLocation || deviceName || "Unknown Venue", alerts: alerts.slice(0, 30) }),
        signal: AbortSignal.timeout(30000),
      });
      const data = await res.json();
      console.log("📄 Report content received, generating .docx...");

      const reportDate = new Date().toLocaleDateString("en-GB", { day: "2-digit", month: "long", year: "numeric" });

      const docChildren: Paragraph[] = [
        new Paragraph({
          children: [new TextRun({ text: `Incident Report — ${deviceLocation || deviceName || "Venue"} — ${reportDate}`, bold: true, size: 36, color: "1E3A5F" })],
          alignment: AlignmentType.CENTER,
          spacing: { after: 400 },
        }),
        new Paragraph({
          children: [new TextRun({ text: `Generated by UnifyOS  |  Team BlackBit  |  ${new Date().toLocaleString()}`, size: 18, color: "888888" })],
          alignment: AlignmentType.CENTER,
          spacing: { after: 600 },
        }),
      ];

      const lines = (data.content || "").split("\n");
      for (const line of lines) {
        const trimmed = line.trim();
        if (!trimmed) {
          docChildren.push(new Paragraph({ text: "" }));
        } else if (/^[A-Z][A-Z ]{2,}$/.test(trimmed)) {
          docChildren.push(new Paragraph({
            children: [new TextRun({ text: trimmed, bold: true, size: 26, color: "1E3A5F" })],
            heading: HeadingLevel.HEADING_2,
            spacing: { before: 400, after: 100 },
          }));
        } else {
          docChildren.push(new Paragraph({
            children: [new TextRun({ text: trimmed, size: 22 })],
            spacing: { after: 80 },
          }));
        }
      }

      const doc = new Document({
        creator: "UnifyOS",
        title: `Incident Report — ${deviceLocation || "Venue"}`,
        description: "Generated by UnifyOS Crisis Coordination Platform",
        sections: [{ properties: {}, children: docChildren }],
      });

      const fileName = `incident-report-${Date.now()}.docx`;

      if (Platform.OS === "web") {
        const blob = await Packer.toBlob(doc);
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = fileName;
        a.click();
        URL.revokeObjectURL(url);
        console.log("✅ Incident report downloaded:", fileName);
        Alert.alert("Report Downloaded", `${fileName} has been saved to your Downloads folder.`);
      } else {
        const buffer = await Packer.toBuffer(doc);
        const path = (FileSystem.documentDirectory ?? "") + fileName;
        const bytes = new Uint8Array(buffer);
        let binary = "";
        for (let i = 0; i < bytes.byteLength; i++) binary += String.fromCharCode(bytes[i]);
        const base64 = btoa(binary);
        await FileSystem.writeAsStringAsync(path, base64, { encoding: FileSystem.EncodingType.Base64 });
        const canShare = await Sharing.isAvailableAsync();
        if (canShare) {
          await Sharing.shareAsync(path, {
            mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            dialogTitle: "Share Incident Report",
            UTI: "com.microsoft.word.doc",
          });
        } else {
          Alert.alert("Report Saved", `Saved to: ${path}`);
        }
      }
    } catch (err: any) {
      console.error("❌ Report generation error:", err?.message || err);
      Alert.alert("Report Error", err?.message || "Failed to generate report. Check if the backend is running.");
    } finally {
      setGeneratingReport(false);
    }
  }

  async function handleExportText() {
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
    const content = buildExportText();
    try {
      if (Platform.OS === "web") {
        const blob = new Blob([content], { type: "text/plain" });
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = `unifyos-alerts-${Date.now()}.txt`;
        a.click();
        URL.revokeObjectURL(url);
      } else {
        const path = (FileSystem.documentDirectory ?? "") + `unifyos-alerts-${Date.now()}.txt`;
        await FileSystem.writeAsStringAsync(path, content, { encoding: FileSystem.EncodingType.UTF8 });
        const canShare = await Sharing.isAvailableAsync();
        if (canShare) {
          await Sharing.shareAsync(path, { mimeType: "text/plain", dialogTitle: "Export Alert Log" });
        } else {
          await Share.share({ message: content, title: "UnifyOS Alert Log" });
        }
      }
    } catch {
      await Share.share({ message: content, title: "UnifyOS Alert Log" });
    }
  }

  async function handleExportSheet() {
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
    if (Platform.OS === "ios") {
      ActionSheetIOS.showActionSheetWithOptions(
        {
          options: ["Cancel", "Export as Text Log", "Share via Share Sheet"],
          cancelButtonIndex: 0,
        },
        (idx) => {
          if (idx === 1) handleExportText();
          if (idx === 2) Share.share({ message: buildExportText(), title: "UnifyOS Alerts" });
        }
      );
    } else {
      Alert.alert("Export Alerts", "Choose export format", [
        { text: "Cancel", style: "cancel" },
        { text: "Export as Text Log", onPress: handleExportText },
        { text: "Share", onPress: () => Share.share({ message: buildExportText(), title: "UnifyOS Alerts" }) },
      ]);
    }
  }

  const filters: { key: Filter; label: string; count?: number }[] = [
    { key: "active", label: "Active", count: activeCount },
    { key: "critical", label: "Critical", count: criticalCount },
    { key: "high", label: "High" },
    { key: "medium", label: "Medium" },
    { key: "all", label: "All" },
  ];

  return (
    <View style={[styles.container, { paddingTop: topPad }]}>
      <View style={styles.header}>
        <View>
          <Text style={styles.title}>Alert History</Text>
          <Text style={styles.subtitle}>{alerts.length} total events logged</Text>
        </View>
        <View style={styles.headerActions}>
          <Pressable onPress={handleGenerateReport} style={styles.reportBtn} disabled={generatingReport} accessibilityRole="button">
            <MaterialCommunityIcons name="file-word-outline" size={14} color={Colors.normal} />
            <Text style={styles.reportText}>{generatingReport ? "Generating..." : "Report"}</Text>
          </Pressable>
          <Pressable onPress={handleExportSheet} style={styles.exportBtn} accessibilityRole="button">
            <Feather name="upload" size={14} color={Colors.accent} />
            <Text style={styles.exportText}>Export</Text>
          </Pressable>
          {filteredAlerts.length > 0 && (
            <Pressable onPress={dismissAll} style={styles.clearBtn}>
              <Feather name="check-square" size={14} color={Colors.textSecondary} />
              <Text style={styles.clearText}>Clear</Text>
            </Pressable>
          )}
        </View>
      </View>

      <View style={styles.langSection}>
        <Text style={styles.langLabel}>🌍 Alert Language</Text>
        <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.langRow}>
          {LANGUAGE_FLAGS.map(lang => (
            <Pressable
              key={lang.code}
              onPress={() => handleLanguageSelect(lang.code)}
              style={[styles.langBtn, selectedLanguage === lang.code && styles.langBtnActive]}
            >
              <Text style={styles.langFlag}>{lang.flag}</Text>
              <Text style={[styles.langCode, selectedLanguage === lang.code && styles.langCodeActive]}>
                {lang.label}
              </Text>
            </Pressable>
          ))}
        </ScrollView>
        {topCritical?.translatedMessages && (
          <View style={styles.criticalBanner}>
            <Text style={styles.criticalBannerText}>
              {topCritical.translatedMessages[selectedLanguage] || topCritical.translatedMessages.en}
            </Text>
          </View>
        )}
      </View>

      <ScrollView
        horizontal
        showsHorizontalScrollIndicator={false}
        style={styles.filterScroll}
        contentContainerStyle={styles.filterContent}
      >
        {filters.map(f => (
          <Pressable
            key={f.key}
            onPress={() => { Haptics.selectionAsync(); setFilter(f.key); }}
            style={[styles.filterChip, filter === f.key && styles.filterChipActive]}
          >
            <Text style={[styles.filterText, filter === f.key && styles.filterTextActive]}>
              {f.label}
            </Text>
            {f.count !== undefined && f.count > 0 && (
              <View style={[styles.filterBadge, filter === f.key && styles.filterBadgeActive]}>
                <Text style={[styles.filterBadgeText, filter === f.key && styles.filterBadgeTextActive]}>
                  {f.count}
                </Text>
              </View>
            )}
          </Pressable>
        ))}
      </ScrollView>

      <ScrollView
        style={styles.scroll}
        contentContainerStyle={[styles.scrollContent, { paddingBottom: bottomPad + 100 }]}
        showsVerticalScrollIndicator={false}
      >
        {filteredAlerts.length === 0 ? (
          <View style={styles.empty}>
            <Feather name="shield" size={40} color={Colors.textMuted} />
            <Text style={styles.emptyTitle}>No alerts</Text>
            <Text style={styles.emptyText}>All systems are operating normally</Text>
          </View>
        ) : (
          filteredAlerts.map(alert => (
            <AlertBanner
              key={String(alert.id)}
              alert={alert}
              selectedLanguage={selectedLanguage}
              onDismiss={() => dismissAlert(alert.id)}
            />
          ))
        )}
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.bg },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
  },
  title: { fontSize: 22, fontFamily: "Inter_700Bold", color: Colors.text, letterSpacing: -0.5 },
  subtitle: { fontSize: 11, fontFamily: "Inter_400Regular", color: Colors.textMuted, marginTop: 1 },
  headerActions: { flexDirection: "row", alignItems: "center", gap: 6 },
  reportBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    backgroundColor: Colors.normalBg,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: Colors.normalBorder,
  },
  reportText: { fontSize: 12, color: Colors.normal, fontFamily: "Inter_500Medium" },
  exportBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    backgroundColor: Colors.accentGlow,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: Colors.accent + "40",
  },
  exportText: { fontSize: 12, color: Colors.accent, fontFamily: "Inter_500Medium" },
  clearBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: Colors.bgCard,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  clearText: { fontSize: 12, color: Colors.textSecondary, fontFamily: "Inter_500Medium" },
  langSection: {
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
    gap: 8,
  },
  langLabel: {
    fontSize: 11,
    fontFamily: "Inter_600SemiBold",
    color: Colors.textSecondary,
    letterSpacing: 0.3,
  },
  langRow: { flexDirection: "row", gap: 8 },
  langBtn: {
    alignItems: "center",
    gap: 2,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: Colors.border,
    backgroundColor: Colors.bgCard,
    minWidth: 48,
  },
  langBtnActive: {
    borderColor: Colors.accent,
    backgroundColor: Colors.accentGlow,
  },
  langFlag: { fontSize: 20 },
  langCode: { fontSize: 9, fontFamily: "Inter_700Bold", color: Colors.textMuted, letterSpacing: 0.3 },
  langCodeActive: { color: Colors.accent },
  criticalBanner: {
    backgroundColor: Colors.criticalBg,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.criticalBorder,
    padding: 14,
  },
  criticalBannerText: {
    fontSize: 20,
    fontFamily: "Inter_700Bold",
    color: Colors.critical,
    textAlign: "center",
    lineHeight: 28,
  },
  filterScroll: { maxHeight: 52, borderBottomWidth: 1, borderBottomColor: Colors.border },
  filterContent: { paddingHorizontal: 16, paddingVertical: 10, gap: 8, flexDirection: "row" },
  filterChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 5,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: Colors.border,
    backgroundColor: Colors.bgCard,
  },
  filterChipActive: { backgroundColor: Colors.accent, borderColor: Colors.accent },
  filterText: { fontSize: 12, color: Colors.textSecondary, fontFamily: "Inter_500Medium" },
  filterTextActive: { color: "#fff" },
  filterBadge: { backgroundColor: Colors.criticalBg, borderRadius: 8, paddingHorizontal: 5, paddingVertical: 1 },
  filterBadgeActive: { backgroundColor: "rgba(255,255,255,0.2)" },
  filterBadgeText: { fontSize: 10, color: Colors.critical, fontFamily: "Inter_700Bold" },
  filterBadgeTextActive: { color: "#fff" },
  scroll: { flex: 1 },
  scrollContent: { padding: 16, gap: 4 },
  empty: { alignItems: "center", paddingVertical: 60, gap: 12 },
  emptyTitle: { fontSize: 18, fontFamily: "Inter_600SemiBold", color: Colors.textSecondary },
  emptyText: { fontSize: 13, color: Colors.textMuted, fontFamily: "Inter_400Regular", textAlign: "center" },
});
