import { Feather } from "@expo/vector-icons";
import React, { useEffect, useState } from "react";
import {
  ActionSheetIOS,
  Alert,
  Platform,
  Pressable,
  ScrollView,
  Share,
  StyleSheet,
  Text,
  View,
} from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import * as Haptics from "expo-haptics";
import AsyncStorage from "@react-native-async-storage/async-storage";
import * as FileSystem from "expo-file-system";
import * as Sharing from "expo-sharing";
import { AlertBanner } from "@/components/AlertBanner";
import { Colors } from "@/constants/colors";
import { useDashboard } from "@/context/DashboardContext";
import { ENV } from "@/config/env";

type Filter = "all" | "active" | "critical" | "high" | "medium";

const LANGUAGE_FLAGS = [
  { code: "en", flag: "🇬🇧", label: "EN", name: "English" },
  { code: "hi", flag: "🇮🇳", label: "HI", name: "Hindi" },
  { code: "ur", flag: "🇵🇰", label: "UR", name: "Urdu" },
  { code: "ar", flag: "🇸🇦", label: "AR", name: "Arabic" },
  { code: "fr", flag: "🇫🇷", label: "FR", name: "French" },
];

export default function AlertsScreen() {
  const insets = useSafeAreaInsets();
  const { alerts, dismissAlert, clearAlertHistory, deviceName, deviceLocation } = useDashboard();
  const [filter, setFilter] = useState<Filter>("active");
  const [selectedLanguage, setSelectedLanguage] = useState("en");
  const [generatingReport, setGeneratingReport] = useState(false);

  const topPad = Platform.OS === "web" ? 67 : insets.top;
  const bottomPad = Platform.OS === "web" ? 34 : insets.bottom;

  useEffect(() => {
    AsyncStorage.getItem("unifyos_language").then(lang => {
      if (lang) setSelectedLanguage(lang);
    });
  }, []);

  const filteredAlerts = alerts.filter(a => {
    if (filter === "active") return !a.dismissed && a.severity !== "NORMAL";
    if (filter === "critical") return a.severity === "CRITICAL";
    if (filter === "high") return a.severity === "HIGH";
    if (filter === "medium") return a.severity === "MEDIUM";
    return true;
  });

  const activeCount = alerts.filter(a => !a.dismissed && a.severity !== "NORMAL").length;
  const criticalCount = alerts.filter(a => a.severity === "CRITICAL").length;

  const topCritical = filteredAlerts.find(a => a.severity === "CRITICAL" && !a.dismissed);

  function handleClearAll() {
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium);
    Alert.alert(
      "Clear All Alerts",
      "This will permanently delete all alert history. This cannot be undone.",
      [
        { text: "Cancel", style: "cancel" },
        {
          text: "Clear All",
          style: "destructive",
          onPress: () => {
            Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
            clearAlertHistory();
            Alert.alert("Cleared", "All alerts have been cleared.");
          },
        },
      ]
    );
  }

  function handleLanguageSelect(code: string) {
    setSelectedLanguage(code);
    AsyncStorage.setItem("unifyos_language", code);
    Haptics.selectionAsync();
  }

  function buildExportText() {
    const header = [
      "═══════════════════════════════════",
      " UnifyOS — Alert Export Log",
      ` Generated: ${new Date().toLocaleString()}`,
      ` Device: ${deviceName}`,
      ` Location: ${deviceLocation}`,
      "═══════════════════════════════════",
      "",
    ].join("\n");

    const body = alerts.slice(0, 100).map(a => [
      `[${a.severity}] — ${new Date(a.createdAt).toLocaleString()}`,
      ` Location: ${a.deviceLocation}`,
      ` Confidence: ${a.confidence}%`,
      a.triggeredSensors?.length ? ` Triggered: ${a.triggeredSensors.join(", ")}` : "",
      ` Message: ${a.message}`,
      a.aiAction ? ` Action: ${a.aiAction}` : "",
      " ─────────────────────────────────",
    ].filter(Boolean).join("\n")).join("\n");

    const footer = [
      "",
      `Total alerts: ${alerts.length}`,
      `Critical: ${alerts.filter(a => a.severity === "CRITICAL").length} | High: ${alerts.filter(a => a.severity === "HIGH").length} | Medium: ${alerts.filter(a => a.severity === "MEDIUM").length}`,
      "Generated by UnifyOS — Team BlackBit",
      "Google Solution Challenge 2026",
    ].join("\n");

    return header + body + footer;
  }

  async function handleGenerateReport() {
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium);
    setGeneratingReport(true);
    try {
      console.log("📄 Generating incident report as text...");

      const now = new Date();
      const reportId = `INC-${Date.now()}`;
      const criticals = alerts.filter(a => a.severity === "CRITICAL");
      const highs = alerts.filter(a => a.severity === "HIGH");
      const mediums = alerts.filter(a => a.severity === "MEDIUM");

      let aiSection = "No AI summary available";
      const topAlert = alerts.find(a => a.severity === "CRITICAL" || a.severity === "HIGH");
      if (topAlert?.aiSummary) aiSection = topAlert.aiSummary;

      const report = [
        "╔══════════════════════════════════════════════════╗",
        "║           UnifyOS — INCIDENT REPORT              ║",
        "╚══════════════════════════════════════════════════╝",
        "",
        `Generated:   ${now.toLocaleString()}`,
        `Incident ID: ${reportId}`,
        `Device:      ${deviceName || "UnifyOS-001"}`,
        `Location:    ${deviceLocation || "Main Lobby"}`,
        "",
        "──────────────────────────────────────────────────",
        "SUMMARY STATISTICS",
        "──────────────────────────────────────────────────",
        `Total Events:    ${alerts.length}`,
        `Critical Events: ${criticals.length}`,
        `High Events:     ${highs.length}`,
        `Medium Events:   ${mediums.length}`,
        "",
        "──────────────────────────────────────────────────",
        "AI ANALYSIS",
        "──────────────────────────────────────────────────",
        aiSection,
        "",
        "──────────────────────────────────────────────────",
        "INCIDENT TIMELINE (LAST 20 EVENTS)",
        "──────────────────────────────────────────────────",
        ...alerts.slice(0, 20).map(a =>
          `[${a.severity}] ${new Date(a.createdAt).toLocaleString()} — ${a.deviceLocation}\n  ${a.message} (Confidence: ${a.confidence}%)\n  Sensors: ${(a.triggeredSensors || []).join(", ") || "N/A"}`
        ),
        "",
        "──────────────────────────────────────────────────",
        "SENSOR DATA ANALYSIS",
        "──────────────────────────────────────────────────",
        "• Temperature monitoring: DHT22 sensors tracked ambient temperature every 2 seconds.",
        "• Smoke detection: MQ-2 gas sensors monitored particulate density in PPM.",
        "• Motion tracking: PIR occupancy sensors detected evacuation patterns.",
        "• Panic buttons: Physical triggers provided manual confirmation data.",
        "• Flame detection: IR photodetector (760–1100 nm) monitored for open flames.",
        "",
        "──────────────────────────────────────────────────",
        "RECOMMENDED ACTIONS",
        "──────────────────────────────────────────────────",
        "1. Review sensor calibration schedules.",
        "2. Conduct staff emergency response drills.",
        "3. Update emergency contact lists.",
        "4. Verify evacuation route signage.",
        "5. Review threshold settings with facility management.",
        "",
        "──────────────────────────────────────────────────",
        "UnifyOS · Team BlackBit · Google Solution Challenge 2026",
        "Hardware: ESP32 · MQ-2 · DHT22 · PIR · IR Flame · Panic Button",
        "Device cost: ₹1,220 per unit",
        "──────────────────────────────────────────────────",
      ].join("\n");

      const fileName = `UnifyOS_Incident_Report_${Date.now()}.txt`;

      if (Platform.OS === "web") {
        const blob = new Blob([report], { type: "text/plain" });
        const url = URL.createObjectURL(blob);
        const anchor = document.createElement("a");
        anchor.href = url;
        anchor.download = fileName;
        anchor.click();
        URL.revokeObjectURL(url);
        Alert.alert("Report Downloaded", `${fileName} has been saved to your Downloads folder.`);
      } else {
        const filePath = (FileSystem.documentDirectory ?? "") + fileName;
        await FileSystem.writeAsStringAsync(filePath, report, {
          encoding: FileSystem.EncodingType.UTF8,
        });
        const canShare = await Sharing.isAvailableAsync();
        if (canShare) {
          await Sharing.shareAsync(filePath, {
            mimeType: "text/plain",
            dialogTitle: "Share Incident Report",
            UTI: "public.plain-text",
          });
        } else {
          Alert.alert("Report Saved", `Saved to: ${filePath}`);
        }
      }

      console.log("📄 Report generated successfully:", fileName);
    } catch (err: any) {
      console.error("❌ Report generation error:", err?.message || err);
      Alert.alert("Report Error", err?.message || "Failed to generate report.");
    } finally {
      setGeneratingReport(false);
    }
  }

  async function handleExportText() {
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
    const content = buildExportText();
    try {
      if (Platform.OS === "web") {
        const blob = new Blob([content], { type: "text/plain" });
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = `unifyos-alerts-${Date.now()}.txt`;
        a.click();
        URL.revokeObjectURL(url);
      } else {
        const path = (FileSystem.documentDirectory ?? "") + `unifyos-alerts-${Date.now()}.txt`;
        await FileSystem.writeAsStringAsync(path, content, { encoding: FileSystem.EncodingType.UTF8 });
        const canShare = await Sharing.isAvailableAsync();
        if (canShare) {
          await Sharing.shareAsync(path, { mimeType: "text/plain", dialogTitle: "Export Alert Log" });
        } else {
          await Share.share({ message: content, title: "UnifyOS Alert Log" });
        }
      }
    } catch {
      await Share.share({ message: content, title: "UnifyOS Alert Log" });
    }
  }

  function buildExportJSON() {
    const payload = {
      exportedAt: new Date().toISOString(),
      platform: "UnifyOS",
      team: "Team BlackBit",
      competition: "Google Solution Challenge 2026",
      device: { name: deviceName, location: deviceLocation },
      summary: {
        total: alerts.length,
        critical: alerts.filter(a => a.severity === "CRITICAL").length,
        high: alerts.filter(a => a.severity === "HIGH").length,
        medium: alerts.filter(a => a.severity === "MEDIUM").length,
        normal: alerts.filter(a => a.severity === "NORMAL").length,
      },
      hardware: {
        model: "UnifyOS-001",
        sensors: ["MQ-2 (Smoke)", "DHT22 (Temp/Humidity)", "PIR (Motion)", "Panic Button", "Flame Sensor (IR)"],
        cost: "₹1,220",
        connectivity: "WiFi (ESP32)",
        battery: "18650 Li-Ion",
      },
      alerts: alerts.slice(0, 200).map(a => ({
        id: a.id,
        severity: a.severity,
        confidence: a.confidence,
        location: a.deviceLocation,
        message: a.message,
        triggeredSensors: a.triggeredSensors,
        aiSummary: a.aiSummary,
        aiAction: a.aiAction,
        createdAt: a.createdAt,
        dismissed: a.dismissed,
      })),
    };
    return JSON.stringify(payload, null, 2);
  }

  async function handleExportJSON() {
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
    console.log("📦 [UnifyOS] Generating JSON export...", { alertCount: alerts.length });
    try {
      const json = buildExportJSON();
      const filename = `unifyos_alerts_${Date.now()}.json`;
      if (Platform.OS === "web") {
        await Share.share({ message: json, title: "UnifyOS JSON Export" });
        return;
      }
      const path = `${FileSystem.documentDirectory}${filename}`;
      await FileSystem.writeAsStringAsync(path, json, { encoding: FileSystem.EncodingType.UTF8 });
      console.log("📦 [UnifyOS] JSON written to:", path);
      const canShare = await Sharing.isAvailableAsync();
      if (canShare) {
        await Sharing.shareAsync(path, { mimeType: "application/json", dialogTitle: "Share JSON Export" });
      } else {
        Alert.alert("Saved", `JSON export saved to:\n${filename}`);
      }
    } catch (e) {
      console.error("📦 [UnifyOS] JSON export error:", e);
      Alert.alert("Error", "Could not export JSON. Try again.");
    }
  }

  async function handleExportSheet() {
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
    if (Platform.OS === "ios") {
      ActionSheetIOS.showActionSheetWithOptions(
        {
          options: ["Cancel", "Export as Text Log", "Export as JSON", "Share via Share Sheet"],
          cancelButtonIndex: 0,
        },
        (idx) => {
          if (idx === 1) handleExportText();
          if (idx === 2) handleExportJSON();
          if (idx === 3) Share.share({ message: buildExportText(), title: "UnifyOS Alerts" });
        }
      );
    } else {
      Alert.alert("Export Alerts", "Choose export format", [
        { text: "Cancel", style: "cancel" },
        { text: "Export as Text Log", onPress: handleExportText },
        { text: "Export as JSON", onPress: handleExportJSON },
        { text: "Share", onPress: () => Share.share({ message: buildExportText(), title: "UnifyOS Alerts" }) },
      ]);
    }
  }

  const filters: { key: Filter; label: string; count?: number }[] = [
    { key: "active", label: "Active", count: activeCount },
    { key: "critical", label: "Critical", count: criticalCount },
    { key: "high", label: "High" },
    { key: "medium", label: "Medium" },
    { key: "all", label: "All" },
  ];

  function getSeverityBarColor(severity: string) {
    if (severity === "CRITICAL") return Colors.critical;
    if (severity === "HIGH") return Colors.high;
    if (severity === "MEDIUM") return Colors.medium;
    return Colors.normal;
  }

  function timeAgo(ts: string) {
    const diff = Date.now() - new Date(ts).getTime();
    const s = Math.floor(diff / 1000);
    if (s < 60) return `${s}s ago`;
    const m = Math.floor(s / 60);
    if (m < 60) return `${m}m ago`;
    const h = Math.floor(m / 60);
    if (h < 24) return `${h}h ago`;
    return `${Math.floor(h / 24)}d ago`;
  }

  return (
    <View style={[styles.container, { paddingTop: topPad }]}>
      <View style={styles.header}>
        <View>
          <Text style={styles.title}>Alert History</Text>
          <Text style={styles.subtitle}>{alerts.length} total events logged</Text>
        </View>
        </View>

      <View style={styles.buttonsRow}>
        <Pressable onPress={handleGenerateReport} style={styles.reportBtn} disabled={generatingReport} accessibilityRole="button">
          <Feather name="file-text" size={12} color="#1A73E8" />
          <Text style={styles.reportText}>{generatingReport ? "…" : "Report"}</Text>
        </Pressable>
        <Pressable onPress={handleExportSheet} style={styles.exportBtn} accessibilityRole="button">
          <Feather name="share" size={12} color="#8BA4D4" />
          <Text style={styles.exportText}>Export</Text>
        </Pressable>
        {alerts.length > 0 && (
          <Pressable onPress={handleClearAll} style={styles.clearBtn}>
            <Feather name="trash-2" size={12} color="#E53935" />
            <Text style={styles.clearText}>Clear</Text>
          </Pressable>
        )}
      </View>

      <View style={styles.langSection}>
        <Text style={styles.langLabel}>🌍 Alert Language</Text>
        <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.langRow}>
          {LANGUAGE_FLAGS.map(lang => (
            <Pressable
              key={lang.code}
              onPress={() => handleLanguageSelect(lang.code)}
              style={[styles.langBtn, selectedLanguage === lang.code && styles.langBtnActive]}
            >
              <Text style={styles.langFlag}>{lang.flag}</Text>
              <Text style={[styles.langCode, selectedLanguage === lang.code && styles.langCodeActive]}>
                {lang.label}
              </Text>
            </Pressable>
          ))}
        </ScrollView>
        {topCritical?.translatedMessages && (
          <View style={styles.criticalBanner}>
            <Text style={styles.criticalBannerText}>
              {topCritical.translatedMessages[selectedLanguage] || topCritical.translatedMessages.en}
            </Text>
          </View>
        )}
      </View>

      <ScrollView
        horizontal
        showsHorizontalScrollIndicator={false}
        style={styles.filterScroll}
        contentContainerStyle={styles.filterContent}
      >
        {filters.map(f => (
          <Pressable
            key={f.key}
            onPress={() => { Haptics.selectionAsync(); setFilter(f.key); }}
            style={[styles.filterChip, filter === f.key && styles.filterChipActive]}
          >
            <Text style={[styles.filterText, filter === f.key && styles.filterTextActive]}>
              {f.label}
            </Text>
            {f.count !== undefined && f.count > 0 && (
              <View style={[styles.filterBadge, filter === f.key && styles.filterBadgeActive]}>
                <Text style={[styles.filterBadgeText, filter === f.key && styles.filterBadgeTextActive]}>
                  {f.count}
                </Text>
              </View>
            )}
          </Pressable>
        ))}
      </ScrollView>

      <ScrollView
        style={styles.scroll}
        contentContainerStyle={[styles.scrollContent, { paddingBottom: bottomPad + 100 }]}
        showsVerticalScrollIndicator={false}
      >
        {filteredAlerts.length === 0 ? (
          <View style={styles.empty}>
            <Feather name="shield" size={40} color={Colors.textMuted} />
            <Text style={styles.emptyTitle}>No alerts</Text>
            <Text style={styles.emptyText}>All systems are operating normally</Text>
          </View>
        ) : (
          filteredAlerts.map(alert => (
            <AlertBanner
              key={String(alert.id)}
              alert={alert}
              selectedLanguage={selectedLanguage}
              onDismiss={() => dismissAlert(alert.id)}
            />
          ))
        )}
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.bg },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
  },
  title: { fontSize: 22, fontFamily: "Inter_700Bold", color: Colors.text, letterSpacing: -0.5 },
  subtitle: { fontSize: 11, fontFamily: "Inter_400Regular", color: Colors.textMuted, marginTop: 1 },
  headerActions: { flexDirection: "row", alignItems: "center", gap: 6 },
  reportBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    backgroundColor: Colors.normalBg,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: Colors.normalBorder,
  },
  reportText: { fontSize: 12, color: Colors.normal, fontFamily: "Inter_500Medium" },
  exportBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    backgroundColor: Colors.accentGlow,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: Colors.accent + "40",
  },
  exportText: { fontSize: 12, color: Colors.accent, fontFamily: "Inter_500Medium" },
  clearBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: Colors.criticalBg,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: Colors.criticalBorder,
  },
  clearText: { fontSize: 12, color: Colors.critical, fontFamily: "Inter_500Medium" },
  langSection: {
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
    gap: 8,
  },
  langLabel: {
    fontSize: 11,
    fontFamily: "Inter_600SemiBold",
    color: Colors.textSecondary,
    letterSpacing: 0.3,
  },
  langRow: { flexDirection: "row", gap: 8 },
  langBtn: {
    alignItems: "center",
    gap: 2,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: Colors.border,
    backgroundColor: Colors.bgCard,
    minWidth: 48,
  },
  langBtnActive: {
    borderColor: Colors.accent,
    backgroundColor: Colors.accentGlow,
  },
  langFlag: { fontSize: 20 },
  langCode: { fontSize: 9, fontFamily: "Inter_700Bold", color: Colors.textMuted, letterSpacing: 0.3 },
  langCodeActive: { color: Colors.accent },
  criticalBanner: {
    backgroundColor: Colors.criticalBg,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.criticalBorder,
    padding: 14,
  },
  criticalBannerText: {
    fontSize: 20,
    fontFamily: "Inter_700Bold",
    color: Colors.critical,
    textAlign: "center",
    lineHeight: 28,
  },
  filterScroll: { maxHeight: 52, borderBottomWidth: 1, borderBottomColor: Colors.border },
  filterContent: { paddingHorizontal: 16, paddingVertical: 10, gap: 8, flexDirection: "row" },
  filterChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 5,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: Colors.border,
    backgroundColor: Colors.bgCard,
  },
  filterChipActive: { backgroundColor: Colors.accent, borderColor: Colors.accent },
  filterText: { fontSize: 12, color: Colors.textSecondary, fontFamily: "Inter_500Medium" },
  filterTextActive: { color: "#fff" },
  filterBadge: { backgroundColor: Colors.criticalBg, borderRadius: 8, paddingHorizontal: 5, paddingVertical: 1 },
  filterBadgeActive: { backgroundColor: "rgba(255,255,255,0.2)" },
  filterBadgeText: { fontSize: 10, color: Colors.critical, fontFamily: "Inter_700Bold" },
  filterBadgeTextActive: { color: "#fff" },
  scroll: { flex: 1 },
  scrollContent: { padding: 16, gap: 4 },
  empty: { alignItems: "center", paddingVertical: 60, gap: 12 },
  emptyTitle: { fontSize: 18, fontFamily: "Inter_600SemiBold", color: Colors.textSecondary },
  emptyText: { fontSize: 13, color: Colors.textMuted, fontFamily: "Inter_400Regular", textAlign: "center" },
});
