import { Feather } from "@expo/vector-icons";
import React, { useEffect, useState } from "react";
import { Platform, Pressable, ScrollView, Share, StyleSheet, Text, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import * as Haptics from "expo-haptics";
import AsyncStorage from "@react-native-async-storage/async-storage";
import * as FileSystem from "expo-file-system";
import * as Sharing from "expo-sharing";
import { AlertBanner } from "@/components/AlertBanner";
import { Colors } from "@/constants/colors";
import { useDashboard } from "@/context/DashboardContext";

type Filter = "all" | "active" | "critical" | "high" | "medium";

const LANGUAGE_FLAGS = [
  { code: "en", flag: "🇬🇧", label: "EN" },
  { code: "hi", flag: "🇮🇳", label: "HI" },
  { code: "ar", flag: "🇸🇦", label: "AR" },
  { code: "fr", flag: "🇫🇷", label: "FR" },
  { code: "es", flag: "🇪🇸", label: "ES" },
  { code: "zh", flag: "🇨🇳", label: "ZH" },
  { code: "ja", flag: "🇯🇵", label: "JA" },
  { code: "de", flag: "🇩🇪", label: "DE" },
  { code: "ru", flag: "🇷🇺", label: "RU" },
];

export default function AlertsScreen() {
  const insets = useSafeAreaInsets();
  const { alerts, dismissAlert } = useDashboard();
  const [filter, setFilter] = useState<Filter>("active");
  const [selectedLanguage, setSelectedLanguage] = useState("en");

  const topPad = Platform.OS === "web" ? 67 : insets.top;
  const bottomPad = Platform.OS === "web" ? 34 : insets.bottom;

  useEffect(() => {
    AsyncStorage.getItem("unifyos_language").then(lang => {
      if (lang) setSelectedLanguage(lang);
    });
  }, []);

  const filteredAlerts = alerts.filter(a => {
    if (filter === "active") return !a.dismissed && a.severity !== "NORMAL";
    if (filter === "critical") return a.severity === "CRITICAL";
    if (filter === "high") return a.severity === "HIGH";
    if (filter === "medium") return a.severity === "MEDIUM";
    return true;
  });

  const activeCount = alerts.filter(a => !a.dismissed && a.severity !== "NORMAL").length;
  const criticalCount = alerts.filter(a => a.severity === "CRITICAL").length;
  const hasHighOrCritical = alerts.some(a => (a.severity === "CRITICAL" || a.severity === "HIGH") && !a.dismissed);

  const dismissAll = () => {
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium);
    filteredAlerts.forEach(a => dismissAlert(a.id));
  };

  async function handleExportLog() {
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
    const lines = alerts.slice(0, 100).map(a =>
      `[${new Date(a.createdAt).toLocaleString()}] ${a.severity} | ${a.deviceLocation} | Conf: ${a.confidence}% | ${a.message}`
    );
    const content = [
      "UnifyOS Alert Export Log",
      `Exported: ${new Date().toLocaleString()}`,
      `Total: ${alerts.length} events`,
      "----------------------------------------",
      ...lines,
      "----------------------------------------",
      "Generated by UnifyOS — Team BlackBit",
    ].join("\n");

    try {
      if (Platform.OS === "web") {
        const blob = new Blob([content], { type: "text/plain" });
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = `unifyos-alerts-${Date.now()}.txt`;
        a.click();
        URL.revokeObjectURL(url);
      } else {
        const path = (FileSystem.documentDirectory ?? "") + `unifyos-alerts-${Date.now()}.txt`;
        await FileSystem.writeAsStringAsync(path, content, { encoding: FileSystem.EncodingType.UTF8 });
        const canShare = await Sharing.isAvailableAsync();
        if (canShare) {
          await Sharing.shareAsync(path, { mimeType: "text/plain", dialogTitle: "Export Alert Log" });
        } else {
          await Share.share({ message: content, title: "UnifyOS Alert Log" });
        }
      }
    } catch {
      await Share.share({ message: content, title: "UnifyOS Alert Log" });
    }
  }

  function handleLanguageSelect(code: string) {
    setSelectedLanguage(code);
    AsyncStorage.setItem("unifyos_language", code);
    Haptics.selectionAsync();
  }

  const filters: { key: Filter; label: string; count?: number }[] = [
    { key: "active", label: "Active", count: activeCount },
    { key: "critical", label: "Critical", count: criticalCount },
    { key: "high", label: "High" },
    { key: "medium", label: "Medium" },
    { key: "all", label: "All" },
  ];

  return (
    <View style={[styles.container, { paddingTop: topPad }]}>
      <View style={styles.header}>
        <View>
          <Text style={styles.title}>Alert History</Text>
          <Text style={styles.subtitle}>{alerts.length} total events logged</Text>
        </View>
        <View style={styles.headerActions}>
          <Pressable onPress={handleExportLog} style={styles.exportBtn} accessibilityRole="button" accessibilityLabel="Export alert log">
            <Feather name="download" size={14} color={Colors.accent} />
            <Text style={styles.exportText}>Export Log</Text>
          </Pressable>
          {filteredAlerts.length > 0 && (
            <Pressable onPress={dismissAll} style={styles.clearBtn}>
              <Feather name="check-square" size={14} color={Colors.textSecondary} />
              <Text style={styles.clearText}>Clear all</Text>
            </Pressable>
          )}
        </View>
      </View>

      <ScrollView
        horizontal
        showsHorizontalScrollIndicator={false}
        style={styles.filterScroll}
        contentContainerStyle={styles.filterContent}
      >
        {filters.map(f => (
          <Pressable
            key={f.key}
            onPress={() => { Haptics.selectionAsync(); setFilter(f.key); }}
            style={[styles.filterChip, filter === f.key && styles.filterChipActive]}
          >
            <Text style={[styles.filterText, filter === f.key && styles.filterTextActive]}>
              {f.label}
            </Text>
            {f.count !== undefined && f.count > 0 && (
              <View style={[styles.filterBadge, filter === f.key ? styles.filterBadgeActive : null]}>
                <Text style={[styles.filterBadgeText, filter === f.key && styles.filterBadgeTextActive]}>
                  {f.count}
                </Text>
              </View>
            )}
          </Pressable>
        ))}
      </ScrollView>

      {hasHighOrCritical && (
        <View style={styles.langSection}>
          <Text style={styles.langLabel}>Emergency Language</Text>
          <ScrollView
            horizontal
            showsHorizontalScrollIndicator={false}
            contentContainerStyle={styles.langRow}
          >
            {LANGUAGE_FLAGS.map(lang => (
              <Pressable
                key={lang.code}
                onPress={() => handleLanguageSelect(lang.code)}
                style={[
                  styles.langBtn,
                  selectedLanguage === lang.code && styles.langBtnActive,
                ]}
              >
                <Text style={styles.langFlag}>{lang.flag}</Text>
                <Text style={[styles.langCode, selectedLanguage === lang.code && styles.langCodeActive]}>
                  {lang.label}
                </Text>
              </Pressable>
            ))}
          </ScrollView>
          {filteredAlerts.length > 0 && (filteredAlerts[0].severity === "CRITICAL" || filteredAlerts[0].severity === "HIGH") && filteredAlerts[0].translatedMessages && (
            <View style={styles.translatedMsgBox}>
              <Text style={styles.translatedMsg}>
                {filteredAlerts[0].translatedMessages[selectedLanguage] || filteredAlerts[0].translatedMessages["en"]}
              </Text>
            </View>
          )}
        </View>
      )}

      <ScrollView
        style={styles.scroll}
        contentContainerStyle={[styles.scrollContent, { paddingBottom: bottomPad + 100 }]}
        showsVerticalScrollIndicator={false}
      >
        {filteredAlerts.length === 0 ? (
          <View style={styles.empty}>
            <Feather name="shield" size={40} color={Colors.textMuted} />
            <Text style={styles.emptyTitle}>No alerts</Text>
            <Text style={styles.emptyText}>All systems are operating normally</Text>
          </View>
        ) : (
          filteredAlerts.map(alert => (
            <AlertBanner
              key={alert.id}
              alert={alert}
              selectedLanguage={selectedLanguage}
              onDismiss={() => dismissAlert(alert.id)}
            />
          ))
        )}
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.bg,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
  },
  title: {
    fontSize: 22,
    fontFamily: "Inter_700Bold",
    color: Colors.text,
    letterSpacing: -0.5,
  },
  subtitle: {
    fontSize: 11,
    fontFamily: "Inter_400Regular",
    color: Colors.textMuted,
    marginTop: 1,
  },
  headerActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  exportBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    backgroundColor: Colors.accentGlow,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: Colors.accent + "40",
  },
  exportText: {
    fontSize: 12,
    color: Colors.accent,
    fontFamily: "Inter_500Medium",
  },
  clearBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: Colors.bgCard,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  clearText: {
    fontSize: 12,
    color: Colors.textSecondary,
    fontFamily: "Inter_500Medium",
  },
  filterScroll: {
    maxHeight: 52,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
  },
  filterContent: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    gap: 8,
    flexDirection: "row",
  },
  filterChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 5,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: Colors.border,
    backgroundColor: Colors.bgCard,
  },
  filterChipActive: {
    backgroundColor: Colors.accent,
    borderColor: Colors.accent,
  },
  filterText: {
    fontSize: 12,
    color: Colors.textSecondary,
    fontFamily: "Inter_500Medium",
  },
  filterTextActive: {
    color: "#fff",
  },
  filterBadge: {
    backgroundColor: Colors.criticalBg,
    borderRadius: 8,
    paddingHorizontal: 5,
    paddingVertical: 1,
  },
  filterBadgeActive: {
    backgroundColor: "rgba(255,255,255,0.2)",
  },
  filterBadgeText: {
    fontSize: 10,
    color: Colors.critical,
    fontFamily: "Inter_700Bold",
  },
  filterBadgeTextActive: {
    color: "#fff",
  },
  langSection: {
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 6,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
    gap: 6,
  },
  langLabel: {
    fontSize: 10,
    fontFamily: "Inter_600SemiBold",
    color: Colors.textMuted,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  langRow: {
    flexDirection: "row",
    gap: 8,
    paddingBottom: 2,
  },
  langBtn: {
    alignItems: "center",
    gap: 2,
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.border,
    backgroundColor: Colors.bgCard,
    minWidth: 44,
  },
  langBtnActive: {
    borderColor: Colors.critical,
    backgroundColor: Colors.criticalBg,
  },
  langFlag: {
    fontSize: 18,
  },
  langCode: {
    fontSize: 9,
    fontFamily: "Inter_600SemiBold",
    color: Colors.textMuted,
    letterSpacing: 0.3,
  },
  langCodeActive: {
    color: Colors.critical,
  },
  translatedMsgBox: {
    backgroundColor: Colors.criticalBg,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.criticalBorder,
    padding: 12,
    marginTop: 4,
  },
  translatedMsg: {
    fontSize: 16,
    fontFamily: "Inter_700Bold",
    color: Colors.critical,
    textAlign: "center",
    lineHeight: 22,
  },
  scroll: { flex: 1 },
  scrollContent: {
    padding: 16,
    gap: 4,
  },
  empty: {
    alignItems: "center",
    paddingVertical: 60,
    gap: 12,
  },
  emptyTitle: {
    fontSize: 18,
    fontFamily: "Inter_600SemiBold",
    color: Colors.textSecondary,
  },
  emptyText: {
    fontSize: 13,
    color: Colors.textMuted,
    fontFamily: "Inter_400Regular",
    textAlign: "center",
  },
});
